### ISSUE TITLE
Request to add new project `rules_graalvm`

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/continuous-integration#1724]
[https://github.com/sgammon/rules_graalvm](https://github.com/sgammon/rules_graalvm)

- [ ] My project is part of the bazelbuild GitHub organization.
- [x] My project is a rules set of a GitHub organization other than bazelbuild.
- [x] I want to test the following project on Bazel CI: https://github.com/sgammon/rules_graalvm
- [x] I confirm that the project has a `.bazelci/presubmit.yml` file.

Thank you! :)

**Comment by meteorcloudy** [comment]
> My project is part of the bazelbuild GitHub organization.

Sorry, currently we are not accepting new projects outside of bazelbuild org. We are working on expanding our fleet, we'll maybe revisit this in the future. Thanks for your understanding!

**Comment by meteorcloudy** [comment]
I'm leaning to approve this request since rules_graalvm is actually a dependency of Bazel now:
https://github.com/bazelbuild/bazel/blob/08df6f1ebeaccb43d3aac1058f8d9e28e11acd2b/MODULE.bazel#L27

**Comment by meteorcloudy** [comment]
I've created a new pipeline for rules_graalvm. But the .bazelci/presubmit.yml doesn't look right: https://buildkite.com/bazel/rules-graalvm/builds/1#018d12ce-a6b3-477f-b373-8d3dc3d75948

**Comment by meteorcloudy** [comment]
Note that the presubmit.yml file format for normal Bazel CI pipeline is different from the BCR ones, it should not contain `bcr_test_module`. Please check the doc at: https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#basic-syntax

**Comment by sgammon** [comment]
@meteorcloudy Thanks for reviving this, I was actually thinking of pinging again. I'll take a look at the presubmit; I don't think it's been tested much before.

**Comment by meteorcloudy** [comment]
This is still not fixed: https://buildkite.com/bazel/rules-graalvm/builds/2#018d14b8-f04a-4934-95ea-c2bc489e6aaa

I think you'll need to merge the two tasks together.
```
yaml.composer.ComposerError: expected a single document in the stream
  in ".bazelci/presubmit.yml", line 2, column 1
but found another document
  in ".bazelci/presubmit.yml", line 19, column 1
```

**Comment by sgammon** [comment]
@meteorcloudy Sorry about that. I've dropped the second document, it's just one YAML document now. I tried to test the command locally but got stuck. I hate to stab in the dark here; if there is a recommended way to test Bazel CI locally (or on my repo), or manually trigger builds etc, I'm happy to follow it.

Otherwise, just tag me if that doesn't work.

**Comment by sgammon** [comment]
@meteorcloudy I see the latest run failed because of a [new issue](https://buildkite.com/bazel/rules-graalvm/builds/3#018d19df-53b4-426c-9f42-3ac321263b69); I've fixed that as well.

**Comment by meteorcloudy** [comment]
@sgammon I'm reaching you out in Bazel Slack, we can add you as a maintainer of this pipeline and set up presubmit for this repo if you want.

**Comment by meteorcloudy** [comment]
This is the latest run: https://buildkite.com/bazel/rules-graalvm/builds/4#_

**Comment by sgammon** [comment]
Thanks @meteorcloudy. I'll check my Slack. In the meantime, this looks like a formatting err now, and that the tests themselves passed. Progress! Should be an easy fix now.

<img width="418" alt="Screenshot 2024-01-18 at 3 29 05 AM" src="https://github.com/bazelbuild/continuous-integration/assets/171897/f8c34491-f8f1-4959-a2fa-020624f56e05">

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/rules-graalvm/builds/32 is still failing on Bazel CI. @sgammon Can you fix the build? Otherwise, there is no meaning running on Bazel CI.

**Comment by sgammon** [comment]
@meteorcloudy yes, I will take a look today; sorry, with these storms in California I have been offline.

**Comment by sgammon** [comment]
@meteorcloudy Thank you for your help getting this working 😁. `rules_graalvm` is building smoothly now in Bazel CI.

**Comment by meteorcloudy** [comment]
Awesome, we can also add it to the downstream pipeline, so that if it's broken by Bazel@HEAD, you'll get notification!
