### ISSUE TITLE
Flakes due to missing python packages

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/continuous-integration#2122]
https://buildkite.com/bazel/rules-rust-rustlang/builds/12763#019369d0-adaf-48ab-aca7-067df6313621
I've noticed this on a few jobs recently
```
$ curl -sS https://raw.githubusercontent.com/bazelbuild/continuous-integration/master/buildkite/bazelci.py?1732647102 -o bazelci.py
python3 bazelci.py runner --task=crate_universe_examples_macos
Traceback (most recent call last):
  File "/Users/buildkite/builds/bk-macos-arm64-0n05/bazel/rules-rust-rustlang/bazelci.py", line 34, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
🚨 Error: The command exited with status 1
^^^ +++
user command error: exit status 1
```

**Comment by meteorcloudy** [comment]
Hopefully this is resolved after we recreated all macOS VMs.

**Comment by UebelAndre** [comment]
https://buildkite.com/bazel/rules-rust-rustlang/builds/14169#01953a9b-3e3e-481c-958c-35ae8377bb1d

I don't have bandwidth to be associating all failed builds with these issues but CI is definitely still seeing a number of flakes at some regularity. I don't know if there's a way to manually trigger runs against rules_rust but various flakes happen there all the time and that would be a great way to repro and run these down. We also aren't doing anything insane in our tests so I'm convinced these are issues in either this code or buildkite.

**Comment by meteorcloudy** [comment]
I checked the latest failures in https://buildkite.com/bazel/rules-rust-rustlang/builds?branch=main, they all seem to be https://github.com/bazelbuild/continuous-integration/issues/2183, which we have a fix rolling out right now.
